Algoritmo "Algoritmo idade entre 13 e 19"

Var
   idade : inteiro

Inicio
      Escreval("Insira a sua idade: ")
      Leia (idade)
      Escreval
      Se ((idade >= 13) e (idade <= 19)) então
         Escreval("Você tem entre 13 e 19 anos.")
         Escreval
      Senão
           Escreval("Você tem menos de 13 anos ou mais de 19 anos.")
           Escreval
      Fimse
   
Fimalgoritmo