Algoritmo "Algoritmo número maior ou menor"

Var
   num1, num2 : real

Inicio
   Escreval("Insira um número: ")
   Leia (num1)
   Escreval
   Escreval("Insira outro número: ")
   Leia (num2)
   Escreval
   Se num1 > num2 então
      Escreval("O primeiro número inserido é maior que o segundo.")
      Escreval
   Senão
        Escreval("O segundo número inserido é maior que o primeiro.")
        Escreval
   Fimse
   
Fimalgoritmo