Algoritmo "Algoritmo soma e multiplicação"

Var
   num, num2, multiplicacao : real

Inicio
      Escreval("Insira o primeiro número da operação: ")
      Leia (num)
      Escreval
      Escreval("Insira o segundo número da operação: ")
      Leia (num2)
      Escreval
      multiplicacao <- (num + num2) * 2
      Escreval("O resultado da operação é: ", multiplicacao)
      Escreval
   
Fimalgoritmo